name: DummyDepender
requirements: []
dependencies: 
  - Dummy

targets:
  startup:
    after:
      - Dummy.startup
  shutdown:
    before:
      - Dummy.shutdown
  post_init:
    function: post_init
    after:
      - DummyDepender.startup
  run:
    function: run
    after:
      - DummyDepender.post_init