services:
  platform:
    build: 
      context: ..
      dockerfile: ./Dockerfile
      target: deploy
    ports:
      - 7889:7889
    volumes:
      - ./data:/satop/data
  
  all_plugins:
    extends: platform
    volumes:
      - ../satop_plugins:/satop/data/plugins
    command: --install-plugin-requirements

  dev:
    build: 
      dockerfile: ../Dockerfile
      target: devel
    ports:
      - 7889:7889
    volumes:
      - ..:/satop
      - ./data:/satop/data
    environment:
      - SATOP_DATA_ROOT=/satop/docker/data
    entrypoint: 
      - "bash"
      - "-c"
      - "pip install -e /satop && python -m satop_platform -vv --install-plugin-requirements"
  
  devcontainer:
    build: 
      dockerfile: ../Dockerfile
      target: devel
    ports:
      - 7889:7889
    volumes:
      - ..:/ws
      - ./data:/satop/data
    environment:
      - SATOP_DATA_ROOT=/satop/data
    command: ["sleep", "infinity"]
