services:
  platform:
    build: ..
    ports:
      - 7889:7889
    volumes:
      - ./data:/satop/data
  
  all_plugins:
    extends: platform
    volumes:
      - ../satop_plugins:/satop/data/plugins
    command: --install-plugin-requirements
    
